### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by ShiinHunter** [Idleon-Companion/IdleonCompanion#180] opened 2021-09-08 03:57 UTC
# Bug Report

**when i copy the link to share my build, the link is broken**

-I just clicked to copy my build link and it's broken for both me and other people

- ![bug report](https://user-images.githubusercontent.com/90299973/132444101-310b0702-5558-43e9-a42c-b49b40d30462.png)

---

**Details**

SO:Windows
Browser:Chrome
Idleon Companion Version (0.3.0 (Site Redesign) | August 2021):

**Comment by adapap** [comment] 2021-09-10 15:54
Duplicate of #167

**Closed by adapap** 2021-09-10 15:54 UTC
Labels: bug

**Comment by ShiinHunter** [comment] 2021-09-10 22:30
it's not just for me that it's broken, that's the problem, for others too.

Em sex., 10 de set. de 2021 às 12:55, Adam Papenhausen <
***@***.***> escreveu:

**Comment by Musimaniac** [comment] 2021-09-10 22:42
The problem is fixed, I just opened your build. try again, please
